# Analyzer -> Engines -> JavaScript -> config.rb
#
# Configuration for JavaScript engine

module Analyzer
  module Engines
    module Javascript

      class Config
        CATEGORY = {
            "eslint.rules.accessor-pairs" => "bug risk",
            "eslint.rules.block-scoped-var" => "bug risk",
            "eslint.rules.callback-return" => "bug risk",
            "eslint.rules.comma-dangle" => "bug risk",
            "eslint.rules.complexity" => "complexity",
            "eslint.rules.consistent-return" => "bug risk",
            "eslint.rules.curly" => "clarity",
            "eslint.rules.default-case" => "bug risk",
            "eslint.rules.dot-location" => "clarity",
            "eslint.rules.dot-notation" => "clarity",
            "eslint.rules.eqeqeq" => "bug risk",
            "eslint.rules.global-require" => "clarity",
            "eslint.rules.guard-for-in" => "bug risk",
            "eslint.rules.handle-callback-err" => "bug risk",
            "eslint.rules.init-declarations" => "clarity",
            "eslint.rules.max-statements" => "complexity",
            "eslint.rules.no-alert" => "bug risk",
            "eslint.rules.no-caller" => "compatibility",
            "eslint.rules.no-case-declarations" => "bug risk",
            "eslint.rules.no-catch-shadow" => "bug risk",
            "eslint.rules.no-cond-assign" => "bug risk",
            "eslint.rules.no-console" => "bug risk",
            "eslint.rules.no-constant-condition" => "bug risk",
            "eslint.rules.no-control-regex" => "bug risk",
            "eslint.rules.no-debugger" => "bug risk",
            "eslint.rules.no-delete-var" => "bug risk",
            "eslint.rules.no-div-regex" => "bug risk",
            "eslint.rules.no-dupe-args" => "bug risk",
            "eslint.rules.no-dupe-keys" => "bug risk",
            "eslint.rules.no-duplicate-case" => "bug risk",
            "eslint.rules.no-else-return" => "clarity",
            "eslint.rules.no-empty" => "bug risk",
            "eslint.rules.no-empty-character-class" => "bug risk",
            "eslint.rules.no-empty-label" => "bug risk",
            "eslint.rules.no-empty-pattern" => "bug risk",
            "eslint.rules.no-eq-null" => "bug risk",
            "eslint.rules.no-eval" => "Security",
            "eslint.rules.no-ex-assign" => "bug risk",
            "eslint.rules.no-extend-native" => "bug risk",
            "eslint.rules.no-extra-bind" => "bug risk",
            "eslint.rules.no-extra-boolean-cast" => "bug risk",
            "eslint.rules.no-extra-parens" => "bug risk",
            "eslint.rules.no-extra-semi" => "bug risk",
            "eslint.rules.no-fallthrough" => "bug risk",
            "eslint.rules.no-floating-decimal" => "clarity",
            "eslint.rules.no-func-assign" => "bug risk",
            "eslint.rules.no-implicit-coercion" => "bug risk",
            "eslint.rules.no-implied-eval" => "Security",
            "eslint.rules.no-inner-declarations" => "compatibility",
            "eslint.rules.no-invalid-regexp" => "bug risk",
            "eslint.rules.no-invalid-this" => "bug risk",
            "eslint.rules.no-irregular-whitespace" => "compatibility",
            "eslint.rules.no-iterator" => "compatibility",
            "eslint.rules.no-label-var" => "bug risk",
            "eslint.rules.no-labels" => "bug risk",
            "eslint.rules.no-lone-blocks" => "bug risk",
            "eslint.rules.no-loop-func" => "bug risk",
            "eslint.rules.no-magic-numbers" => "clarity",
            "eslint.rules.no-mixed-requires" => "clarity",
            "eslint.rules.no-multi-spaces" => "bug risk",
            "eslint.rules.no-multi-str" => "compatibility",
            "eslint.rules.no-native-reassign" => "bug risk",
            "eslint.rules.no-negated-in-lhs" => "bug risk",
            "eslint.rules.no-new" => "bug risk",
            "eslint.rules.no-new-func" => "clarity",
            "eslint.rules.no-new-require" => "clarity",
            "eslint.rules.no-new-wrappers" => "bug risk",
            "eslint.rules.no-obj-calls" => "bug risk",
            "eslint.rules.no-octal" => "compatibility",
            "eslint.rules.no-octal-escape" => "compatibility",
            "eslint.rules.no-param-reassign" => "bug risk",
            "eslint.rules.no-path-concat" => "bug risk",
            "eslint.rules.no-process-env" => "bug risk",
            "eslint.rules.no-process-exit" => "bug risk",
            "eslint.rules.no-proto" => "compatibility",
            "eslint.rules.no-redeclare" => "bug risk",
            "eslint.rules.no-regex-spaces" => "bug risk",
            "eslint.rules.no-restricted-modules" => "Security",
            "eslint.rules.no-return-assign" => "bug risk",
            "eslint.rules.no-script-url" => "Security",
            "eslint.rules.no-self-compare" => "bug risk",
            "eslint.rules.no-sequences" => "bug risk",
            "eslint.rules.no-shadow" => "bug risk",
            "eslint.rules.no-shadow-restricted-names" => "bug risk",
            "eslint.rules.no-sparse-arrays" => "bug risk",
            "eslint.rules.no-sync" => "bug risk",
            "eslint.rules.no-throw-literal" => "clarity",
            "eslint.rules.no-undef" => "bug risk",
            "eslint.rules.no-undef-init" => "bug risk",
            "eslint.rules.no-undefined" => "compatibility",
            "eslint.rules.no-unexpected-multiline" => "bug risk",
            "eslint.rules.no-unreachable" => "bug risk",
            "eslint.rules.no-unused-expressions" => "bug risk",
            "eslint.rules.no-unused-vars" => "bug risk",
            "eslint.rules.no-use-before-define" => "compatibility",
            "eslint.rules.no-useless-call" => "bug risk",
            "eslint.rules.no-useless-concat" => "bug risk",
            "eslint.rules.no-void" => "compatibility",
            "eslint.rules.no-warning-comments" => "bug risk",
            "eslint.rules.no-with" => "compatibility",
            "eslint.rules.np-dupe-keys" => "bug risk",
            "eslint.rules.radix" => "bug risk",
            "eslint.rules.use-isnan" => "bug risk",
            "eslint.rules.use-strict" => "bug risk",
            "eslint.rules.valid-jsdoc" => "clarity",
            "eslint.rules.valid-typeof" => "bug risk",
            "eslint.rules.vars-on-top" => "clarity",
            "eslint.rules.wrap-iife" => "clarity",
            "eslint.rules.yoda" => "clarity"
          }.freeze

          CATEGORY_WEIGHTS = {
            "bug risk" =>
          }
      end

    end
  end
end