# Analyzer -> Engines -> JavaScript -> config.rb
#
# Configuration for JavaScript engine

module Analyzer
  module Engines
    module Javascript

      class Config
        DEFAULT_POINT = 50000
        RESULT_CONFIG = '-c ~/.eslintrc -f checkstyle'

        CATEGORY = {
            "eslint.rules.accessor-pairs" => ["bug risk", 50000],
            "eslint.rules.block-scoped-var" => ["bug risk", 50000],
            "eslint.rules.callback-return" => ["bug risk", 50000],
            "eslint.rules.comma-dangle" => ["bug risk", 50000],
            "eslint.rules.consistent-return" => ["bug risk", 50000],
            "eslint.rules.complexity" => ["complexity", 100000],
            "eslint.rules.default-case" => ["bug risk", 50000],
            "eslint.rules.curly" => ["clarity", 50000],
            "eslint.rules.dot-location" => ["clarity", 50000],
            "eslint.rules.eqeqeq" => ["bug risk", 50000],
            "eslint.rules.dot-notation" => ["clarity", 50000],
            "eslint.rules.guard-for-in" => ["bug risk", 50000],
            "eslint.rules.handle-callback-err" => ["bug risk", 50000],
            "eslint.rules.global-require" => ["clarity", 50000],
            "eslint.rules.init-declarations" => ["clarity", 50000],
            "eslint.rules.no-alert" => ["bug risk", 50000],
            "eslint.rules.max-statements" => ["complexity", 100000],
            "eslint.rules.no-case-declarations" => ["bug risk", 50000],
            "eslint.rules.no-catch-shadow" => ["bug risk", 50000],
            "eslint.rules.no-cond-assign" => ["bug risk", 50000],
            "eslint.rules.no-console" => ["bug risk", 50000],
            "eslint.rules.no-constant-condition" => ["bug risk", 50000],
            "eslint.rules.no-control-regex" => ["bug risk", 50000],
            "eslint.rules.no-debugger" => ["bug risk", 50000],
            "eslint.rules.no-delete-var" => ["bug risk", 50000],
            "eslint.rules.no-div-regex" => ["bug risk", 50000],
            "eslint.rules.no-dupe-args" => ["bug risk", 50000],
            "eslint.rules.no-dupe-keys" => ["bug risk", 50000],
            "eslint.rules.no-duplicate-case" => ["bug risk", 50000],
            "eslint.rules.no-caller" => ["compatibility", 50000],
            "eslint.rules.no-empty" => ["bug risk", 50000],
            "eslint.rules.no-empty-character-class" => ["bug risk", 50000],
            "eslint.rules.no-empty-label" => ["bug risk", 50000],
            "eslint.rules.no-empty-pattern" => ["bug risk", 50000],
            "eslint.rules.no-eq-null" => ["bug risk", 50000],
            "eslint.rules.no-else-return" => ["clarity", 50000],
            "eslint.rules.no-ex-assign" => ["bug risk", 50000],
            "eslint.rules.no-extend-native" => ["bug risk", 50000],
            "eslint.rules.no-extra-bind" => ["bug risk", 50000],
            "eslint.rules.no-extra-boolean-cast" => ["bug risk", 50000],
            "eslint.rules.no-extra-parens" => ["bug risk", 50000],
            "eslint.rules.no-extra-semi" => ["bug risk", 50000],
            "eslint.rules.no-fallthrough" => ["bug risk", 50000],
            "eslint.rules.no-eval" => "Security",
            "eslint.rules.no-func-assign" => ["bug risk", 50000],
            "eslint.rules.no-implicit-coercion" => ["bug risk", 50000],
            "eslint.rules.no-floating-decimal" => ["clarity", 50000],
            "eslint.rules.no-implied-eval" => "Security",
            "eslint.rules.no-invalid-regexp" => ["bug risk", 50000],
            "eslint.rules.no-invalid-this" => ["bug risk", 50000],
            "eslint.rules.no-inner-declarations" => ["compatibility", 50000],
            "eslint.rules.no-irregular-whitespace" => ["compatibility", 50000],
            "eslint.rules.no-label-var" => ["bug risk", 50000],
            "eslint.rules.no-labels" => ["bug risk", 50000],
            "eslint.rules.no-lone-blocks" => ["bug risk", 50000],
            "eslint.rules.no-loop-func" => ["bug risk", 50000],
            "eslint.rules.no-iterator" => ["compatibility", 50000],
            "eslint.rules.no-magic-numbers" => ["clarity", 50000],
            "eslint.rules.no-multi-spaces" => ["bug risk", 50000],
            "eslint.rules.no-mixed-requires" => ["clarity", 50000],
            "eslint.rules.no-native-reassign" => ["bug risk", 50000],
            "eslint.rules.no-negated-in-lhs" => ["bug risk", 50000],
            "eslint.rules.no-new" => ["bug risk", 50000],
            "eslint.rules.no-multi-str" => ["compatibility", 50000],
            "eslint.rules.no-new-func" => ["clarity", 50000],
            "eslint.rules.no-new-wrappers" => ["bug risk", 50000],
            "eslint.rules.no-obj-calls" => ["bug risk", 50000],
            "eslint.rules.no-new-require" => ["clarity", 50000],
            "eslint.rules.no-octal" => ["compatibility", 50000],
            "eslint.rules.no-param-reassign" => ["bug risk", 50000],
            "eslint.rules.no-path-concat" => ["bug risk", 50000],
            "eslint.rules.no-process-env" => ["bug risk", 50000],
            "eslint.rules.no-process-exit" => ["bug risk", 50000],
            "eslint.rules.no-octal-escape" => ["compatibility", 50000],
            "eslint.rules.no-redeclare" => ["bug risk", 50000],
            "eslint.rules.no-regex-spaces" => ["bug risk", 50000],
            "eslint.rules.no-proto" => ["compatibility", 50000],
            "eslint.rules.no-return-assign" => ["bug risk", 50000],
            "eslint.rules.no-restricted-modules" => "Security",
            "eslint.rules.no-self-compare" => ["bug risk", 50000],
            "eslint.rules.no-sequences" => ["bug risk", 50000],
            "eslint.rules.no-shadow" => ["bug risk", 50000],
            "eslint.rules.no-shadow-restricted-names" => ["bug risk", 50000],
            "eslint.rules.no-sparse-arrays" => ["bug risk", 50000],
            "eslint.rules.no-sync" => ["bug risk", 50000],
            "eslint.rules.no-script-url" => "Security",
            "eslint.rules.no-undef" => ["bug risk", 50000],
            "eslint.rules.no-undef-init" => ["bug risk", 50000],
            "eslint.rules.no-throw-literal" => ["clarity", 50000],
            "eslint.rules.no-unexpected-multiline" => ["bug risk", 50000],
            "eslint.rules.no-unreachable" => ["bug risk", 50000],
            "eslint.rules.no-unused-expressions" => ["bug risk", 50000],
            "eslint.rules.no-unused-vars" => ["bug risk", 50000],
            "eslint.rules.no-undefined" => ["compatibility", 50000],
            "eslint.rules.no-useless-call" => ["bug risk", 50000],
            "eslint.rules.no-useless-concat" => ["bug risk", 50000],
            "eslint.rules.no-use-before-define" => ["compatibility", 50000],
            "eslint.rules.no-warning-comments" => ["bug risk", 50000],
            "eslint.rules.no-void" => ["compatibility", 50000],
            "eslint.rules.np-dupe-keys" => ["bug risk", 50000],
            "eslint.rules.radix" => ["bug risk", 50000],
            "eslint.rules.use-isnan" => ["bug risk", 50000],
            "eslint.rules.use-strict" => ["bug risk", 50000],
            "eslint.rules.no-with" => ["compatibility", 50000],
            "eslint.rules.valid-typeof" => ["bug risk", 50000],
            "eslint.rules.valid-jsdoc" => ["clarity", 50000],
            "eslint.rules.vars-on-top" => ["clarity", 50000],
            "eslint.rules.wrap-iife" => ["clarity", 50000],
            "eslint.rules.yoda" => ["clarity", 50000]
          }.freeze
      end

    end
  end
end